//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medie
    {
        public int id_medie { get; set; }
        public Nullable<int> id_elev { get; set; }
        public Nullable<int> id_prof { get; set; }
        public Nullable<int> id_materie { get; set; }
        public Nullable<int> media { get; set; }
        public Nullable<int> semestru { get; set; }
    
        public virtual Elev Elev { get; set; }
        public virtual Prof_materie Prof_materie { get; set; }
    }
}
