//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specializare_materie
    {
        public int id_specializare { get; set; }
        public int id_materie { get; set; }
        public Nullable<bool> teza { get; set; }
    
        public virtual Materie Materie { get; set; }
        public virtual Specializare Specializare { get; set; }
    }
}
